apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
spec:
  selector:
    matchLabels:
      name: web
  replicas: 1
  template:
    metadata:
      name: web
      labels:
        name: web
    spec:
      containers:
        - name: web
          image: ghcr.io/saenyakorn/web:0.0.7
          ports:
            - containerPort: 3000
              name: web-svc
          env:
            - name: PORT
              value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: web
spec:
  type: ClusterIP
  selector:
    name: web
  ports:
    - name: default
      protocol: TCP
      port: 3000
      targetPort: web-svc
