apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    spec:
      containers:
        - name: docs
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 800Mi
