apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deployment.yaml

commonLabels:
  app: api-dev

nameSuffix: -dev

images:
- name: api
  newName: ghcr.io/saenyakorn/monorepo-demo/api
  newTag: dev-a0dedf3705be0105e6bed88041eca8e4fab823e4

resources:
- ../../base
