name: Build and Publish Docker 

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      image-prefix:
        required: true
        type: string
      tag:
        type: string
        default: latest
      registry: 
        type: string
        default: ghcr.io
      push: 
        type: boolean
        default: false
      node-version:
        type: string
        default: 16.x
    secrets:
      username:
        required: true
      password:
        required: true
    outputs:
      image: 
        description: The output image name
        value: ${{ jobs.build-and-publish-docker.outputs.image }}
      
jobs:
  build-and-publish-docker:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image.outputs.IMAGE }}
      imageid: ${{ steps.build-and-push.outputs.imageid }}
      digest: ${{ steps.build-and-push.outputs.digest }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Output image
        id: image
        run: echo "IMAGE=${{ inputs.registry }}/${{ inputs.app-name }}:${{ inputs.tag }}" >> $GITHUB_OUTPUT 

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        id: build-and-push
        with:
          context: .
          file: apps/${{ inputs.app-name }}/Dockerfile
          tags: ${{ steps.image.outputs.IMAGE }}
          push: ${{ inputs.push }}

      - name: Show Docker image
        run: docker images